---

- hosts: "{{ hosts }}"
  vars:
    tomcat_dir: "{{ lookup('ini', 'CONNECT_APPS section=Common_Settings file={{ configFile }}') }}/{{ lookup('ini', 'TOMCAT_DIR section=Common_Settings file={{ configFile }}') }}"
  tasks:
    - name: Check tomcat installed version
      win_shell: .\version.bat | find "Server version"  | %{ [regex]::matches($_, "\d{1,2}(\.\d{1,3})+") } | %{ $_.Value }
      args:
        chdir: "{{ tomcat_dir }}\\bin"
      register: tomcat_version_output
      failed_when: "'FAILED' in curr_tomcat_version.stderr"

    - set_fact:
        tomcat_version: "{{ tomcat_version_output.stdout | regex_replace('\\r\\n', '') }}"

