#####################################################################################
# Date            Version            Change
# 01/03/2019      1.0                created (previous)
# 11/04/2019      2.0                backlog fixes and new features (current)
#####################################################################################
---

- hosts: "{{ hosts }}"
  vars:
    tomcats: "{{ lookup('ini', 'TOMCATS section={{ section }} file={{ configFile }}').split(',') }}"
    tomcat_zip: "{{ lookup('ini', 'TOMCAT_ZIP section=Common_Settings file={{ configFile }}') }}"
    tomcat_version: "{{ lookup('ini', 'TOMCAT_VERSION section=Common_Settings file={{ configFile }}') }}"
    tomcat_dir: "{{ lookup('ini', 'CONNECT_APPS section=Common_Settings file={{ configFile }}') }}/{{ lookup('ini', 'TOMCAT_DIR section=Common_Settings file={{ configFile }}') }}"
    software_dir: "{{ lookup('ini', 'CONNECT_SOFTWARE section=Common_Settings file={{ configFile}}') }}"
    service_name: "{{ lookup('ini', 'SERVICE_NAME section=Common_Settings file={{ configFile }}') }}"
    regexps:
      - { port: "Server port=\"[\\d]*\" shutdown=\"SHUTDOWN\"", replace: "Server port=\"{{ port|int - 75 }}\" shutdown=\"SHUTDOWN\"" }
      - { port: "Connector port=\"[\\d]*\" protocol=\"HTTP/1.1\"", replace: "Connector port=\"{{ port }}\" protocol=\"HTTP/1.1\"" }
      - { port: "redirectPort=\"[\\d]*\"", replace: "redirectPort=\"{{ port|int + 363 }}\"" }
      - { port: "Connector port=\"[\\d]*\" protocol=\"AJP/1.3\"", replace: "Connector port=\"{{ port|int - 71 }}\" protocol=\"AJP/1.3\"" }

  tasks:

    - include_vars:
        file: "/etc/ansible/group_vars_{{ deployment_environment }}/tomcat.yml"
        name: tomcat
      tags:
       - updateTomcat
      no_log: true

    - name: Install Tomcats
      include_tasks: installTomcat.yml tomcat_port={{ item }}
      with_items:
        - "{{ tomcats }}"
