---

- hosts: "{{ hosts }}"
  vars:
    section: "{{ hostvars[inventory_hostname]['label'] }}"
    tomcats: "{{ lookup('ini', 'TOMCATS section={{ section }} file={{ configFile }}').split(',') }}"
    tomcat_dir: "{{ lookup('ini', 'CONNECT_APPS section=Common_Settings file={{ configFile }}') }}/{{ lookup('ini', 'TOMCAT_DIR section=Common_Settings file={{ configFile }}') }}"
    tomcat_version: "{{ lookup('ini', 'TOMCAT_VERSION section=Common_Settings file={{ configFile }}') }}"
    service_name: "{{ lookup('ini', 'SERVICE_NAME section=Common_Settings file={{ configFile }}') }}"

  tasks:
    - name: Change tomcat ports
      include_tasks: regexToTomcat.yml tomcat_port={{ item }}
      with_items:
        - "{{ tomcats }}"

    - name: Change tomcat ports
      include_tasks: addManager.yml tomcat_port={{ item }}
      with_items:
        - "{{ tomcats }}"
