---

- hosts: "{{ hosts }}"
  vars:
    tomcat_service_prefix: "{{ lookup('ini', 'SERVICE_NAME section=Common_Settings file={{ configFile }}') }}"
  tasks:
    - name: Start all tomcat services
      win_shell: Get-Service | Where-Object {$_.displayName.StartsWith("{{ tomcat_service_prefix }}-")} | Start-Service

