#####################################################################################
# Date            Version            Change
# 01/03/2019      1.0                created (previous)
# 11/04/2019      2.0                backlog fixes and new features (current)
#####################################################################################
---

# Stop a service forcefully
- hosts: "{{ hosts }}"
  vars:
    service_name:
  tasks:
    - name: Stop service "{{ service_name }}"
      win_shell: taskkill /fi /f "Services eq {{ service_name }}"
