---

# Stop a service forcefully
- hosts: "{{ hosts }}"
  vars:
    service_name:
  tasks:
    - name: Stop service "{{ service_name }}"
      win_shell: taskkill /fi /f "Services eq {{ service_name }}"
