#####################################################################################
# Date            Version            Change
# 01/03/2019      1.0                created (previous)
# 11/04/2019      2.0                backlog fixes and new features (current)
#####################################################################################
---

- hosts: "{{ hosts }}"
  vars:
    tomcat_service_prefix: "{{ lookup('ini', 'SERVICE_NAME section=Common_Settings file={{ configFile }}') }}"
  tasks:
    - name: Stop all tomcat services
#      win_shell: Get-Service | Where-Object {$_.displayName.StartsWith("Apache-Tomcat-")} | Stop-Service
      win_shell: taskkill /f /fi "Services eq {{ tomcat_service_prefix }}-*"

